const teams = [
  "Qatar",
  "Ecuador",
  "Senegal",
  "Netherlands",
  "England",
  "Iran",
  "USA",
  "Wales",
  "Argentina",
  "Saudi Arabia",
  "Mexico",
  "Poland",
  "France",
  "Australia",
  "Denmark",
  "Tunisia",
  "Spain",
  "Costa Rica",
  "Germany",
  "Japan",
  "Belgium",
  "Canada",
  "Morocco",
  "Croatia",
  "Brazil",
  "Serbia",
  "Switzerland",
  "Cameroon",
  "Portugal",
  "Ghana",
  "Uruguay",
  "South Korea",
];

const people = [
  "Abiola Ogunjobi",
  "Adam Sachs",
  "Akumu Bavon",
  "Albert Akrong",
  "Alex Marufu",
  "Alicia",
  "Alistair",
  "Amo Parker Prince",
  "Amy Rodgers",
  "Andrea Jonker",
  "Andrea Potgieter",
  "Anelda Knoetze",
  "Angie Martins",
  "Angus Charter",
  "Annetjie Morris",
  "annie",
  "Anri Coetzee",
  "Anu Apiti",
  "Aobakwe",
  "Aqeel Abader",
  "Arnold Vosloo",
  "Ashleigh Neimann",
  "Ashleigh Niemann",
  "Ashleigh Tasker",
  "Bafana Mahamba",
  "Barbara Visser",
  "Ben Landman",
  "Bessie",
  "Blessing Kabungaidze",
  "Blessing Raolane",
  "Boipelo Zuma",
  "Bongani Maseko",
  "Boniface Thuku",
  "Brad Pieter",
  "Bradley Digby Benoy",
  "Brent Steyn",
  "Byron McCarthy",
  "Carla Bramham",
  "Casmir Chukwuma",
  "Cassie Perkett",
  "Caylin Firer",
  "Charlene Nel",
  "Chase le Roux",
  "Chucks Nwachukwu",
  "Claire Turya",
  "Collins Zimba",
  "Cosmas Augostino",
  "Danell van Tonder",
  "Daniel Harten",
  "Daniel Maartens",
  "Daniel Maartens",
  "Darrah Paslovsky",
  "Dean Tawonezvi",
  "Deni Buys",
  "Derik Sadiki",
  "Desmond Poongavanam",
  "Devon Carter",
  "Devon Hayes",
  "Dhash",
  "Dor Golombick",
  "Dumisile Hlengwa",
  "Eden Plein",
  "Edward Vincent",
  "Erastus Ruiru",
  "Eteshan Reddy",
  "Ezrqn Kemboi",
  "Fabian Ruszczynski",
  "Faiyaaz Khan",
  "Faron Gottlieb",
  "Gabin Kabuya",
  "Garth Smith",
  "Garth Smith",
  "George Sebastiaan van Heerden",
  "Gerald Neves",
  "Gregor Simpson",
  "Gregory Hill",
  "Habeeb Ajide",
  "Haniel Chidavose",
  "Hilton Kudyahakudadirwe",
  "Ilhaam Tagodien",
  "Isaack Seshoka",
  "Itumeleng Morei",
  "Jaco Munnik",
  "Jameel Geduld",
  "Jamie Chennells",
  "Janke Bester",
  "Jené Hattingh",
  "Jeremy Kithome",
  "Jessica van Heerden",
  "Joma Simeon",
  "Jonathan Heugh",
  "Jonathon Tasker",
  "Joseph Senabulya",
  "Josh Duckworth",
  "Joshua Kodhe",
  "Joshua Roelf",
  "Julian Mackay",
  "Justin Korkie",
  "Justin Mullins",
  "Kamogelo Lesejane",
  "Katlego Williams",
  "Kaylin Maharaj",
  "Kelly Grewar",
  "Kezian Naidoo",
  "Khats",
  "Kimberley Mugadza",
  "Kuda Mhizha",
  "Kudakwashe Mupeni",
  "Kudzai Mabika",
  "Lethlhogonolo Sekwati",
  "Letlhogonolo Sekwati",
  "Lewis Evans",
  "Lolo Gladys",
  "Lolontle Moatshe",
  "Luke Hunt",
  "Luke Parr",
  "Lungz Dlamini",
  "Maipato Nkebenyane",
  "Marco de Agrela",
  "Mark Venter",
  "Martin Wright",
  "Marylin Ndlovu",
  "Mathias Angule",
  "Matt",
  "Matthew Davies",
  "Matthew fainman",
  "Matthew Lane",
  "McAnthony",
  "Megan Harper",
  "Melinda Mazongo",
  "Membathisi Mcetywa",
  "Michael Manuel",
  "Micheal Oluwasegun",
  "Mihle Damoyi",
  "Moffat Gitau",
  "Mongezi Mabena",
  "Moses Idowu",
  "Moses Mulondo",
  "Moses Ngwerume",
  "Mugove Machaka",
  "Nadia Criticos",
  "Naomi Hoogeweegen",
  "Ncedile Nkonyana",
  "Ndivhuwo Khabubu",
  "Nicanor Korir",
  "Nick Martin",
  "Nickson Mwangi",
  "Nikita Batlis",
  "Oliver Green",
  "Olivier Richie",
  "Paula Eltringham",
  "Penuel Nkosi",
  "Princess Siphokazi Nkomo",
  "Prudence Sibongile Zwane",
  "Rahul Singh",
  "Raikane More",
  "Raphael",
  "Riané Hattingh",
  "Robert Menin",
  "Rodgers Tanui",
  "Roland Bitalo",
  "Romeo Zikalala",
  "Ronald Hove",
  "Ryan Seal",
  "Samuel Ocran",
  "Samuel Takarinda",
  "Samuel Thiong'o",
  "Sanvir Dessai",
  "Sarah Druce",
  "Sarah Mills",
  "Seretla Mahlagare",
  "Shaeen Kumalaseelan",
  "Shanique Jooste",
  "Shawn Whelan",
  "Sibusiso Massango",
  "Simoné De Vos",
  "Simphiwe Zulu",
  "Sonke Gumede",
  "Sree",
  "Stephen Byarugaba",
  "Stewart Chamirai",
  "Storm Kippie",
  "Sunkanmi Ijatuyi",
  "Tadiwa Lesely Musekiwa",
  "Tagara Mutuma",
  "Tamsin Thom",
  "Tanaka Lance Gombera",
  "Tanaka Seda",
  "Tapiwa Joel Mudavanhu",
  "Tapiwanashe Shoshore",
  "Teddy Kekana",
  "Terri",
  "Tessa Pratt",
  "Thabang Khoza",
  "Thabiso Kenneth Mokone",
  "Thabiso Sekhwela",
  "Thandolwethu Mpofu",
  "Thapelo Mothapo",
  "Thato Banda",
  "Thato Nwamadi",
  "Thomas Shields",
  "Timi Tejumola",
  "Tinashe Makaza",
  "Tlangelani Mboweni",
  "Tlou Rammala",
  "Trevor Kurland",
  "Tyrell Adkins",
  "Ugochukwu Mmaduekwe",
  "Uzukhanye Nohe",
  "Viwe Kakana",
  "Willem Fourie",
  "Willem Wouter Viljoen",
  "Yatin Badal",
  "Zac",
  "Zoleka Kubheka",
];

module.exports = {
  teams,
  people,
};
